root_dir = "output"

global_templates_vars = { my_var = 15 }

templates = { lit_template = "my_var: {{ my_var }}" }

templates_dir = "output/templates"


package_dirs = ["packages", "apps"]
pnpm_config = { onlyBuiltDependencies = [
  "esbuild",
  "rolldown",
  "@tailwindcss/oxide",
] }

[package_presets.custom_templates_test]
generate_templates = [
  { template = "subdir/nested.j2", output = "nested.yaml" },
  { template = "abc.j2", output = "with_global_var.yaml" },
  { template = "abc.j2", output = "with_override.yaml", context = { my_var = 20 } },
  { template = { name = "literal_inlined", content = "my_var: {{ my_var }}" }, output = "literal_inlined.yaml" },
  { template = "lit_template", output = "literal_from_config.yaml" },
]

[package_presets.alt2]
name = "abc2"
package_json = "abc"
dir = "packages/mypkg"
moonrepo = { tasks = { command = "abc" }, config = { data = "abc" } }

[package_json_presets.base]
scripts = { abc = "abc", bcd = "bcd" }
repository = "myrepo"
license = "Apache 2.0"
keywords = ["hobbits", "isengard"]
homepage = "hobbits.com"
bugs = { url = "hobbits.com", email = "hello@hobbits.com" }
author = { name = "vincenzo", email = "vincenzo@hobbits.com", url = "hobbits.com" }
files = ["index.ts", "index2.ts"]
engines = { node = "23.0.0", deno = "2.2" }
os = ["darwin", "linux"]
cpu = ["x64", "arm64"]

[package_json_presets.svelte.dev_dependencies]
vite = "catalog:"
svelte = "catalog:svelte"
tailwind = "catalog:tailwind"

[package_json_presets.abc]
name = "abc"
bugs = { workspace = true }
workspaces = ["one", "two"]
main = "dist/index.js"
extends = ["svelte", "base"]
contributors = [
  { name = "vincenzo", email = "vincenzo@hobbits.com", url = "hobbits.com" },
  { name = "vincenzo", email = "vincenzo@hobbits.com", url = "hobbits.com" },
  { name = "vincenzo", email = "vincenzo@hobbits.com", url = "hobbits.com" },
]
maintainers = [
  { name = "vincenzo", email = "vincenzo@hobbits.com", url = "hobbits.com" },
  { name = "vincenzo", email = "vincenzo@hobbits.com", url = "hobbits.com" },
  { name = "vincenzo", email = "vincenzo@hobbits.com", url = "hobbits.com" },
]
peer_dependencies = { somepkg = "1.0.0", otherpkg = "2.0.0" }
optional_dependencies = { somepkg = "1.0.0", otherpkg = "2.0.0" }
bundled_dependencies = { somepkg = "1.0.0", otherpkg = "2.0.0" }
man = ["./man/foo.1", "./man/foo.2"]
config = { something = { setting = true, other = "something" }, otherThing = "some_setting" }
publish_config = { access = "public", tag = "mytag", registry = "hobbits.com", something = { setting = true, other = "something" }, otherThing = "some_setting" }


[package_json_presets.abc.dependencies]
my-app = "^1.0.0"
my-app2 = "^1.0.0"

[package_json_presets.abc.dev_dependencies]
my-app = "^1.0.0"

[package_json_presets.abc.metadata]
custom = { something = "abc", other = "abc" }

[package_json_presets.abc.metadata.pnpm]
onlyBuildDependencies = ["esbuild"]

[moonrepo.toolchain]
fileGroups = ["abc", "bcd"]

[pre_commit]

[[pre_commit.repos]]
path = "local"

[[pre_commit.repos.hooks]]
id = "oxlint"
name = "oxlint"
entry = "oxlint"
language = "system"
files = '\.svelte$|\.js$|\.ts$'
types = ["file"]
