root_dir = "tests/output"

global_templates_vars = { my_var = 15 }

templates = { lit_template = "my_var: {{ my_var }}" }

templates_dir = "tests/templates"

[typescript]
pnpm_config = { onlyBuiltDependencies = [
  "esbuild",
  "rolldown",
  "@tailwindcss/oxide",
] }

[typescript.package_presets.test]
name = "test_package"
package_json = "extended"
dir = "packages/test_package"
moonrepo = { tasks = { command = "abc" }, config = { data = "abc" } }

[typescript.people]
aragorn = { name = "Aragorn", email = "aragorn@middleeath.com", url = "aragorn.middleearth.com" }
legolas = { name = "Legolas", email = "legolas@middleeath.com", url = "legolas.middleearth.com" }

[typescript.package_json_presets.base]
keywords = ["hobbits", "isengard"]
bugs = { url = "hobbits.com", email = "hello@hobbits.com" }
author = { name = "Frodo", email = "Frodo@hobbits.com", url = "hobbits.com" }

[typescript.package_json_presets.abc]
extends = ["base"]
contributors = ["aragorn", "legolas"]
maintainers = ["aragorn", "legolas"]
