root_dir = "output"
repository = "myrepo"

[package_json.abc]
package_name = "abc"

[package_json.abc.dependencies]
my-app = "^1.0.0"
my-app2 = "^1.0.0"

[package_json.abc.dev_dependencies]
my-app = "^1.0.0"

[package_json.abc.metadata]
custom = { something = "abc", other = "abc" }

[package_json.abc.metadata.pnpm]
onlyBuildDependencies = ["esbuild"]

[moonrepo.toolchain]
fileGroups = ["abc", "bcd"]

[pre_commit]

[[pre_commit.repos]]
path = "local"

[[pre_commit.repos.hooks]]
id = "oxlint"
name = "oxlint"
entry = "oxlint"
language = "system"
files = '\.svelte$|\.js$|\.ts$'
types = ["file"]

[package_presets.alt2]
name = "abc2"
package_json = "abc"
dir = "packages/mypkg"
moonrepo = { tasks = { command = "abc" }, config = { data = "abc" } }
